/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package danhmuc.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the phieugiahan service. Represents a row in the &quot;phieugiahan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link danhmuc.model.impl.phieugiahanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link danhmuc.model.impl.phieugiahanImpl}.
 * </p>
 *
 * @author LAPTOP
 * @see phieugiahan
 * @see danhmuc.model.impl.phieugiahanImpl
 * @see danhmuc.model.impl.phieugiahanModelImpl
 * @generated
 */
public interface phieugiahanModel extends BaseModel<phieugiahan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phieugiahan model instance should use the {@link phieugiahan} interface instead.
	 */

	/**
	 * Returns the primary key of this phieugiahan.
	 *
	 * @return the primary key of this phieugiahan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phieugiahan.
	 *
	 * @param primaryKey the primary key of this phieugiahan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this phieugiahan.
	 *
	 * @return the ID of this phieugiahan
	 */
	public long getId();

	/**
	 * Sets the ID of this phieugiahan.
	 *
	 * @param id the ID of this phieugiahan
	 */
	public void setId(long id);

	/**
	 * Returns the ngaygiahan of this phieugiahan.
	 *
	 * @return the ngaygiahan of this phieugiahan
	 */
	public Date getNgaygiahan();

	/**
	 * Sets the ngaygiahan of this phieugiahan.
	 *
	 * @param ngaygiahan the ngaygiahan of this phieugiahan
	 */
	public void setNgaygiahan(Date ngaygiahan);

	/**
	 * Returns the phieumuon ID of this phieugiahan.
	 *
	 * @return the phieumuon ID of this phieugiahan
	 */
	public long getPhieumuonId();

	/**
	 * Sets the phieumuon ID of this phieugiahan.
	 *
	 * @param phieumuonId the phieumuon ID of this phieugiahan
	 */
	public void setPhieumuonId(long phieumuonId);

	/**
	 * Returns the xacnhan of this phieugiahan.
	 *
	 * @return the xacnhan of this phieugiahan
	 */
	public long getXacnhan();

	/**
	 * Sets the xacnhan of this phieugiahan.
	 *
	 * @param xacnhan the xacnhan of this phieugiahan
	 */
	public void setXacnhan(long xacnhan);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(danhmuc.model.phieugiahan phieugiahan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<danhmuc.model.phieugiahan> toCacheModel();

	@Override
	public danhmuc.model.phieugiahan toEscapedModel();

	@Override
	public danhmuc.model.phieugiahan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}