/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package danhmuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Sach service. Represents a row in the &quot;sach&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link danhmuc.model.impl.SachModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link danhmuc.model.impl.SachImpl}.
 * </p>
 *
 * @author LAPTOP
 * @see Sach
 * @see danhmuc.model.impl.SachImpl
 * @see danhmuc.model.impl.SachModelImpl
 * @generated
 */
public interface SachModel extends BaseModel<Sach> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sach model instance should use the {@link Sach} interface instead.
	 */

	/**
	 * Returns the primary key of this sach.
	 *
	 * @return the primary key of this sach
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sach.
	 *
	 * @param primaryKey the primary key of this sach
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this sach.
	 *
	 * @return the ID of this sach
	 */
	public long getId();

	/**
	 * Sets the ID of this sach.
	 *
	 * @param id the ID of this sach
	 */
	public void setId(long id);

	/**
	 * Returns the name of this sach.
	 *
	 * @return the name of this sach
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this sach.
	 *
	 * @param name the name of this sach
	 */
	public void setName(String name);

	/**
	 * Returns the theloai i d of this sach.
	 *
	 * @return the theloai i d of this sach
	 */
	public long getTheloaiID();

	/**
	 * Sets the theloai i d of this sach.
	 *
	 * @param theloaiID the theloai i d of this sach
	 */
	public void setTheloaiID(long theloaiID);

	/**
	 * Returns the soluong of this sach.
	 *
	 * @return the soluong of this sach
	 */
	public long getSoluong();

	/**
	 * Sets the soluong of this sach.
	 *
	 * @param soluong the soluong of this sach
	 */
	public void setSoluong(long soluong);

	/**
	 * Returns the nxb of this sach.
	 *
	 * @return the nxb of this sach
	 */
	@AutoEscape
	public String getNxb();

	/**
	 * Sets the nxb of this sach.
	 *
	 * @param nxb the nxb of this sach
	 */
	public void setNxb(String nxb);

	/**
	 * Returns the tacgia of this sach.
	 *
	 * @return the tacgia of this sach
	 */
	@AutoEscape
	public String getTacgia();

	/**
	 * Sets the tacgia of this sach.
	 *
	 * @param tacgia the tacgia of this sach
	 */
	public void setTacgia(String tacgia);

	/**
	 * Returns the masach of this sach.
	 *
	 * @return the masach of this sach
	 */
	@AutoEscape
	public String getMasach();

	/**
	 * Sets the masach of this sach.
	 *
	 * @param masach the masach of this sach
	 */
	public void setMasach(String masach);

	/**
	 * Returns the ke of this sach.
	 *
	 * @return the ke of this sach
	 */
	public long getKe();

	/**
	 * Sets the ke of this sach.
	 *
	 * @param ke the ke of this sach
	 */
	public void setKe(long ke);

	/**
	 * Returns the tang of this sach.
	 *
	 * @return the tang of this sach
	 */
	public long getTang();

	/**
	 * Sets the tang of this sach.
	 *
	 * @param tang the tang of this sach
	 */
	public void setTang(long tang);

	/**
	 * Returns the noidung of this sach.
	 *
	 * @return the noidung of this sach
	 */
	@AutoEscape
	public String getNoidung();

	/**
	 * Sets the noidung of this sach.
	 *
	 * @param noidung the noidung of this sach
	 */
	public void setNoidung(String noidung);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(danhmuc.model.Sach sach);

	@Override
	public int hashCode();

	@Override
	public CacheModel<danhmuc.model.Sach> toCacheModel();

	@Override
	public danhmuc.model.Sach toEscapedModel();

	@Override
	public danhmuc.model.Sach toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}