/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package danhmuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the theloai service. Represents a row in the &quot;theloai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link danhmuc.model.impl.theloaiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link danhmuc.model.impl.theloaiImpl}.
 * </p>
 *
 * @author LAPTOP
 * @see theloai
 * @see danhmuc.model.impl.theloaiImpl
 * @see danhmuc.model.impl.theloaiModelImpl
 * @generated
 */
public interface theloaiModel extends BaseModel<theloai> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a theloai model instance should use the {@link theloai} interface instead.
	 */

	/**
	 * Returns the primary key of this theloai.
	 *
	 * @return the primary key of this theloai
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this theloai.
	 *
	 * @param primaryKey the primary key of this theloai
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this theloai.
	 *
	 * @return the ID of this theloai
	 */
	public long getId();

	/**
	 * Sets the ID of this theloai.
	 *
	 * @param id the ID of this theloai
	 */
	public void setId(long id);

	/**
	 * Returns the name of this theloai.
	 *
	 * @return the name of this theloai
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this theloai.
	 *
	 * @param name the name of this theloai
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(danhmuc.model.theloai theloai);

	@Override
	public int hashCode();

	@Override
	public CacheModel<danhmuc.model.theloai> toCacheModel();

	@Override
	public danhmuc.model.theloai toEscapedModel();

	@Override
	public danhmuc.model.theloai toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}