/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package danhmuc.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import danhmuc.model.phieugiahan;

import danhmuc.service.phieugiahanLocalServiceUtil;

/**
 * The extended model base implementation for the phieugiahan service. Represents a row in the &quot;phieugiahan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link phieugiahanImpl}.
 * </p>
 *
 * @author LAPTOP
 * @see phieugiahanImpl
 * @see danhmuc.model.phieugiahan
 * @generated
 */
public abstract class phieugiahanBaseImpl extends phieugiahanModelImpl
	implements phieugiahan {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phieugiahan model instance should use the {@link phieugiahan} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			phieugiahanLocalServiceUtil.addphieugiahan(this);
		}
		else {
			phieugiahanLocalServiceUtil.updatephieugiahan(this);
		}
	}
}